In [1]:
#import the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

#Load Dataset
walmart = pd.read_csv("walmart_data.csv")
walmart.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category,Purchase
0,1000001,P00069042,F,0-17,10.0,A,2,0.0,3.0,8370.0
1,1000001,P00248942,F,0-17,10.0,A,2,0.0,1.0,15200.0
2,1000001,P00087842,F,0-17,10.0,A,2,0.0,12.0,1422.0
3,1000001,P00085442,F,0-17,10.0,A,2,0.0,12.0,1057.0
4,1000002,P00285442,M,55+,16.0,C,4+,0.0,8.0,7969.0

In [2]:
#Question 1: Basic Metrics & Problem Understanding

#shape of Dataset
print("Shape of data:", walmart.shape)

Shape of data: (269060, 10)

In [3]:
#Datatype of Attributes
print("\nData Types:\n", walmart.dtypes)

Data Types:
 User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                    float64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                float64
Product_Category              float64
Purchase                      float64
dtype: object

In [4]:
#Conversion of categorical columns to "Category"
categorical_cols = ['Gender', 'Age', 'City_Category',
                    'Stay_In_Current_City_Years', 'Marital_Status']

for col in categorical_cols:
    walmart[col] = walmart[col].astype('category')

print(walmart.dtypes)

User_ID                          int64
Product_ID                      object
Gender                        category
Age                           category
Occupation                     float64
City_Category                 category
Stay_In_Current_City_Years    category
Marital_Status                category
Product_Category               float64
Purchase                       float64
dtype: object

In [5]:
#Statistical Summary
walmart.describe()

            User_ID     Occupation  Product_Category       Purchase
count  2.690600e+05  269059.000000     269059.000000  269059.000000
mean   1.002990e+06       8.077975          5.293739    9319.357732
std    1.710685e+03       6.521886          3.745137    4970.738130
min    1.000001e+06       0.000000          1.000000     185.000000
25%    1.001495e+06       2.000000          1.000000    5864.000000
50%    1.003032e+06       7.000000          5.000000    8060.000000
75%    1.004425e+06      14.000000          8.000000   12059.000000
max    1.006040e+06      20.000000         18.000000   23961.000000